import time

print("start the debug exp 1")
print("start the debug exp 2")
print("start the debug exp 3")
print("start the debug exp 4")
print("start the debug exp 5")
print("start the debug exp 6")
print("start the debug exp 7")
print("start the debug exp 8")
print("start the debug exp 9")
print("start the debug exp 10")
print("start the debug exp 11")
print("start the debug exp 12")
print("start the debug exp 13")
time.sleep(60)
print("going to debug mode")
time.sleep(10)
exit(1)
